Save model Using Joblib and Pickle

In [1]:
!pip install joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from sklearn import linear_model
import joblib

In [3]:
df = pd.read_csv("/content/drive/MyDrive/ML_practise_project/homeprices.csv")

In [4]:
df.head

<bound method NDFrame.head of    area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000>

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [6]:
reg.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

Pickle allows you to serialize your python object into a file

In [7]:
with open('reg_pickle','wb') as f:
     pickle.dump(reg,f)

In [8]:
with open('reg_pickle','rb') as f:
     rp = pickle.load(f)

In [9]:
rp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

Joblib can be a replacement of pickle (dump & load), which is more efficient on objects that carry large numpy arrays 

In [10]:
joblib.dump(reg,"reg_joblib")

['reg_joblib']

In [11]:
rj = joblib.load("reg_joblib")

In [12]:
rj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

After applying Regression here Pickle,Joblib gave the same prediction result